### PR TITLE
🔧 MAINTAIN: Add typing

### PR DESCRIPTION
**Pull request by chrisjsewell**
~currently based on top of #112~

- Remove `@property` from `seekable` method (as per BinaryIO)
- Disallow mode in `LazyOpen` (should always be readable binary)
- ~add `__enter__`/`__exit__` methods to `PackedObjectReader`, `CallbackStreamWrapper`, `ZlibLikeBaseStreamDecompresser`, so they won't fail in `add_streamed_objects_to_pack` with `open_streams=True`~

Come across this issue for `get_objects`/`get_object_stream_and_meta`: https://github.com/PyCQA/pylint/issues/3233

Types initially generated with https://github.com/Instagram/MonkeyType

### CODE REVIEW

**Review by ramirezfranciscof — COMMENTED** [review]
Hey, I think this all looks good!

My only question is if it would be possible to separate the addition of type checking from the other changes enumerated in the description or if there is something specific preventing this. Ideally I would have made a PR for each of these two sets of changes, but if that is a bit too much work I would say having two separate commits on this PR should be enough.

**Comment by chrisjsewell** [comment]
@ramirezfranciscof thanks for the review, but the other changes were specifically added issues with the i.e. without them the type checking fails

**Comment by ramirezfranciscof** [comment]
Ah, really? That is very surprising. Can you tell me what kind of problem you were getting for each of those three changes? I'll be very interested in understanding how the typing affects that, since I'm trying to incorporate it myself when I'm coding and may run into these too 😅 .

On the other hand, perhaps it was wrong of me to limit my comment to "the other changes enumerated in the description", as there are also a couple of modifications that were not mentioned there but I was also referring to. For example, there is a modification in the `__init__` of `CallbackStreamWrapper` where `_update_every` and `_since_last_update` get initialized outside of the `if self._callback:` condition. Was this also modified because of the type checking/hinting??

**Comment by chrisjsewell** [comment]
> Was this also modified because of the type checking/hinting??

any changes were because of type checking

**Comment by chrisjsewell** [comment]
> Remove @property from seekable method (as per BinaryIO), Disallow mode in LazyOpen (should always be readable binary), add __enter__/__exit__ methods to PackedObjectReader, CallbackStreamWrapper, ZlibLikeBaseStreamDecompresser, so they won't fail in add_streamed_objects_to_pack with open_streams=True

All these changes are because `PackedObjectReader`, `CallbackStreamWrapper`, `ZlibLikeBaseStreamDecompresser` are intended to mimic a `typing.BinaryIO` object, i.e. what you get from `open("path", mode="rb")`, but they either did this incorrectly, in the case of seekable, or did not include enough of the `BinaryIO` interface, in the case of `__enter__`/`__exit__`.

**Comment by ramirezfranciscof** [comment]
Ah, ok, I see, so these are to fix the interface of `typing.BinaryIO` so it will recognize it when type checking. Although I still don't understand how this relates to the change inside the `__init__` of `CallbackStreamWrapper` 🤔 ...type checking shouldn't go in the implementation inside the methods, no? Is having a `_update_every` and a `_since_last_update` members part of the "interface" of the `typing.BinaryIO`?

However, if this were modifications made "in preparation" for the type checking, this does not prevent us to have them in a first commit and then have a second one for just the type checking. I do agree now that it makes sense to have these on the same PR, but I still think the two commits are valuable to keep separated everything that is behavior-modifying, which would make it much easier to review (meaning not only for reviewing like what I'm doing now, since it is now a bit too late for that, haha, but I mean for revisiting in general if at some point in the future there is any need to debug or understand anything related to these changes).

**Comment by chrisjsewell** [comment]
> the change inside the __init__ of CallbackStreamWrapper 

if instance attributes are set dynamically, I.e in sonde if statements, it means they may not be set and mypy cannot statically determine that. Basically you should generally always set instance attributes with a default value

**Comment by chrisjsewell** [comment]
> if this were modifications made "in preparation" 

if have to disagree with this I’m afraid; they made **because** of typing check failures, not in preparation. The commit would not be reviewable in isolation, since it would claim to fix typing issues that were not yet tested

**Comment by ramirezfranciscof** [comment]
I mean, yeah, I agree that this was the actual order in which things happened / reason why the changes were made. What I am saying is that conceptually the changes can make sense separated ("adapting the interface to comply with `typing.BinaryIO`" + "adding typechecking") and we would be gaining a lot in code/record clarity and development modularity. The logical connection of the changes being made for the typing would still be kept since they are in the same PR, so there is not really anything that is being lost in this reorganization. Am I missing anything here?

**Comment by chrisjsewell** [comment]
>  we would be gaining a lot in code/record clarity and development modularity.

Ah dude, I completely disagree; it won't provide any measurable benefit.

But its really not worth falling out over lol, so my comprise is that I've made this commit and rebased the PR on it:  https://github.com/aiidateam/disk-objectstore/commit/2d2d32c14fb4f5a0068fbbe49a16daf3285aeda8

**Review by ramirezfranciscof — APPROVED** [review]
Mmm ok; I still don't understand what would be the overcomplication here (the two resulting commits should each be simpler than the compound). But I'll agree to the second part, and for the sake of expediency I'll take the compromise.

**Comment by chrisjsewell** [comment]
Thanks 🙏

**Pull request merged**
