### PR TITLE
Fixing mypy issue renaming database.py to db.py

### PR DESCRIPTION
**Pull request by ramirezfranciscof**

### CODE REVIEW

**Comment by ramirezfranciscof** [comment]
I think this fixes the problems with `mypy` that we are having on the aiida repository. If I [understood correctly](https://github.com/python/mypy/issues/9384#issuecomment-761622026), apparently `mypy` now decided to get more opinionated about what we name our files and modules...

Example of error in  aiidateam/aiida-core: see [here](https://github.com/aiidateam/aiida-core/runs/4737628161?check_suite_focus=true).

Example of error in this repo: see [here](https://github.com/aiidateam/disk-objectstore/runs/4695723828?check_suite_focus=true).

The name `objectstore_db.py` was just to do the test, but if you prefer something else let me know and I'll change it.

**Review by chrisjsewell — DISMISSED** [review]
Yeh no worries, if you think this fixes it thats fine by me

**Review by giovannipizzi — APPROVED** [review]
Thanks (also for changing the name from objecstore_db to db!)

**Comment by sphuber** [comment]
@ramirezfranciscof why do you think the renaming of the module fixed the problem? The issue that you link doesn't seem to explain why `database.py` should be problematic. They mentioned `typing.py`, which makes more sense being a problematic name for `mypy`. I don't see why `database.py` should cause any problems.

**Comment by giovannipizzi** [comment]
Apparently using sqla 1.4.29 fixes the problem. I'm going to revert this PR soon and change the dependency of sqla in the pre-commit-config.yaml

**Pull request merged**
